#! /usr/bin/env bash

superwatcher init
superwatcher watch git://github.com/wballard/commitments_server.git ~/commitments
superwatcher watch git://github.com/wballard/commitments_ui.git ~/commitments_ui
superwatcher environment ~/commitments/environment
superwatcher main superforker 8080 ~/commitments ~/commitments_ui
superwatcher restart
