#! /usr/bin/env bash

superwatcher init
superwatcher watch git://github.com/wballard/commitments_server.git ~/commitments_server
superwatcher watch git://github.com/wballard/commitments_ui.git ~/commitments_ui
superwatcher environment ~/commitments/environment
superwatcher main superforker 8080 ~/commitments_server ~/commitments_ui
superwatcher restart
