#!/usr/bin/env bash
source ./environment

if [ ! -d ${COMMITMENTS_ROOT} ]; then
  mkdir -p ${COMMITMENTS_ROOT}
fi
if [ ! -d ${NOTIFY_ROOT} ]; then
  mkdir -p ${NOTIFY_ROOT}
fi
if [ ! -d ${TOKEN_ROOT} ]; then
  mkdir -p ${TOKEN_ROOT}
fi

#make all the directories whole
./token init
./notify init
./commitments init
