#!/usr/bin/env bash
git submodule update --recursive --init
rm -rf node_modules
npm install
rm "./commitments"
ln -s "./node_modules/commitments/bin/commitments" "./commitments"
rm "./notify"
ln -s "./node_modules/notify/bin/notify" "./notify"
rm "./token"
ln -s "./node_modules/token/bin/token" "./token"
rm "./render"
ln -s "./node_modules/render/bin/render" "./render"
rm "./send"
ln -s "./node_modules/send/bin/send" "./send"

source ./environment

if [ ! -d ${COMMITMENTS_ROOT} ]; then
  mkdir -p ${COMMITMENTS_ROOT}
fi
if [ ! -d ${NOTIFY_ROOT} ]; then
  mkdir -p ${NOTIFY_ROOT}
fi
if [ ! -d ${TOKEN_ROOT} ]; then
  mkdir -p ${TOKEN_ROOT}
fi

#make all the directories whole
./token init
./notify init
./commitments init
