#!/usr/bin/env bash
git submodule update --recursive --init
npm install
rm "$(pwd)/commitments"
ln -s "$(pwd)/node_modules/commitments/bin/commitments" "$(pwd)/commitments"
rm "$(pwd)/notify"
ln -s "$(pwd)/node_modules/notify/bin/notify" "$(pwd)/notify"

